{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adswizz",
    "module": "adswizz-sdk",
    "version": "7.2.2-exoplayer2.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "lovchsq5prbcjfiil4hv7jxhry"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.12.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-lite",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-sdk-7.2.2-exoplayer2.12.aar",
          "url": "adswizz-sdk-7.2.2-exoplayer2.12.aar",
          "size": 1985271,
          "sha512": "6e52456fd35a99405790dd5e70729c97c864c7290149f2e8126a96c64a6d3b493eb5beb72ee69065c2237be875ea9456122af3795a3eb2b635a720eb31b9de54",
          "sha256": "5210e4d32085947941fa58d9bde61ab748df39cc69c88fcea9eab4dcd399e93b",
          "sha1": "c2465783da8a8587e76202dd05cf01873bd1033e",
          "md5": "e85f95ad8292e2dcafb0bb7ad14fb1f5"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.12.1"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-sdk-7.2.2-exoplayer2.12.aar",
          "url": "adswizz-sdk-7.2.2-exoplayer2.12.aar",
          "size": 1985271,
          "sha512": "6e52456fd35a99405790dd5e70729c97c864c7290149f2e8126a96c64a6d3b493eb5beb72ee69065c2237be875ea9456122af3795a3eb2b635a720eb31b9de54",
          "sha256": "5210e4d32085947941fa58d9bde61ab748df39cc69c88fcea9eab4dcd399e93b",
          "sha1": "c2465783da8a8587e76202dd05cf01873bd1033e",
          "md5": "e85f95ad8292e2dcafb0bb7ad14fb1f5"
        }
      ]
    }
  ]
}
