{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adswizz",
    "module": "adswizz-wear-sdk",
    "version": "7.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "jv5gwcl7cnctfberj5lcvw65gi"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.wear",
          "module": "wear",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "com.google.android.support",
          "module": "wearable",
          "version": {
            "requires": "2.8.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-wear-sdk-7.3.0.aar",
          "url": "adswizz-wear-sdk-7.3.0.aar",
          "size": 351384,
          "sha512": "dbfb8c35b2595597841fbcb54c7bdc3df4c4484d9a4b113587e91a4f422227ff466328989389fb776a59f517e6e06b894edd00975ba482093823d729ff0e34fa",
          "sha256": "38b14abdf51f36f8ff7a9789d1f247021e481a5c96ba8b6626cc6063e0661935",
          "sha1": "af99cf479c75cf847ead5e7e6c7fad0e14cb12ca",
          "md5": "0d972953711f5b87b14d53c3714580ea"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "adswizz-wear-sdk-7.3.0.aar",
          "url": "adswizz-wear-sdk-7.3.0.aar",
          "size": 351384,
          "sha512": "dbfb8c35b2595597841fbcb54c7bdc3df4c4484d9a4b113587e91a4f422227ff466328989389fb776a59f517e6e06b894edd00975ba482093823d729ff0e34fa",
          "sha256": "38b14abdf51f36f8ff7a9789d1f247021e481a5c96ba8b6626cc6063e0661935",
          "sha1": "af99cf479c75cf847ead5e7e6c7fad0e14cb12ca",
          "md5": "0d972953711f5b87b14d53c3714580ea"
        }
      ]
    }
  ]
}
