{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adswizz",
    "module": "adswizz-sdk",
    "version": "7.3.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "zkguum7s6bdphpl5efvilcc4ta"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-javalite",
          "version": {
            "requires": "3.11.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-sdk-7.3.0.aar",
          "url": "adswizz-sdk-7.3.0.aar",
          "size": 2040273,
          "sha512": "a0bc75fc80c4a3780257fcb16e3fd4418b0b89742b1b2216b6e74f76eea02a036ffa65424bb70d88c73cb87acd8d2620aa18c1982d271efe6f6354bcbb9c8a90",
          "sha256": "75f77fa9ae02b05be38f0d96555c1d84004d498583fb17d5ddfb686147cad5eb",
          "sha1": "bdd3eb999321ebcf8120f4af91d17ccf169ff635",
          "md5": "10bab8140a7ac261e9c1042f20f0be77"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-sdk-7.3.0.aar",
          "url": "adswizz-sdk-7.3.0.aar",
          "size": 2040273,
          "sha512": "a0bc75fc80c4a3780257fcb16e3fd4418b0b89742b1b2216b6e74f76eea02a036ffa65424bb70d88c73cb87acd8d2620aa18c1982d271efe6f6354bcbb9c8a90",
          "sha256": "75f77fa9ae02b05be38f0d96555c1d84004d498583fb17d5ddfb686147cad5eb",
          "sha1": "bdd3eb999321ebcf8120f4af91d17ccf169ff635",
          "md5": "10bab8140a7ac261e9c1042f20f0be77"
        }
      ]
    }
  ]
}
