{
  "formatVersion": "1.1",
  "component": {
    "group": "com.adswizz",
    "module": "adswizz-sdk",
    "version": "7.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.1.1",
      "buildId": "7x46mwardncpvc4d6hlk7hynpy"
    }
  },
  "variants": [
    {
      "name": "runtime",
      "attributes": {
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.10.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-android-extensions-runtime",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-reflect",
          "version": {
            "requires": "1.3.61"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-ads",
          "version": {
            "requires": "18.2.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "1.1.3"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-extensions",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.3.2"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.squareup.moshi",
          "module": "moshi-adapters",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "com.google.protobuf",
          "module": "protobuf-lite",
          "version": {
            "requires": "3.0.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-wearable",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "org.apache.commons",
          "module": "commons-math3",
          "version": {
            "requires": "3.6.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "17.0.0"
          }
        },
        {
          "group": "com.amazonaws",
          "module": "aws-android-sdk-core",
          "version": {
            "requires": "2.17.1"
          }
        },
        {
          "group": "androidx.work",
          "module": "work-runtime-ktx",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-sdk-7.2.2.aar",
          "url": "adswizz-sdk-7.2.2.aar",
          "size": 1979376,
          "sha512": "85423ba82bedc6e45dddb2596f5725d5da3880d61b89ec1481088866450aa481f855ecc3626da02733b6116ccaf86e607e83e391b536ee37b5e5effdaf359388",
          "sha256": "a252917f6e8b0e1336c2fef7a359fe01e0616e6ea779a7a12a4cd4f0d331f61a",
          "sha1": "d12184d807b9590882c20f7efa32b0443364858a",
          "md5": "ffdd9e2bfb237fba4ccdafac00027807"
        }
      ]
    },
    {
      "name": "api",
      "attributes": {
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.google.android.exoplayer",
          "module": "exoplayer",
          "version": {
            "requires": "2.10.0"
          }
        }
      ],
      "files": [
        {
          "name": "adswizz-sdk-7.2.2.aar",
          "url": "adswizz-sdk-7.2.2.aar",
          "size": 1979376,
          "sha512": "85423ba82bedc6e45dddb2596f5725d5da3880d61b89ec1481088866450aa481f855ecc3626da02733b6116ccaf86e607e83e391b536ee37b5e5effdaf359388",
          "sha256": "a252917f6e8b0e1336c2fef7a359fe01e0616e6ea779a7a12a4cd4f0d331f61a",
          "sha1": "d12184d807b9590882c20f7efa32b0443364858a",
          "md5": "ffdd9e2bfb237fba4ccdafac00027807"
        }
      ]
    }
  ]
}
